### ISSUE TITLE
Why do the lanes predicted by CLRNet all start from the edges in VIL-100?

### ISSUE THREAD

**Issue by Core9724** [Sephirex-X/ADNet#3]
Thank you for your excellent work. The visualization results of ADNet are really amazing, but I have a question to ask. I want to know why the anchors of CLRNet are ultimately distributed at the edges of the image. As far as I know, although the anchors of CLRNet, like LineCNN and LaneATT, are pre-defined, their positions and directions can also be learned. Therefore, theoretically, as long as the ground truth does not start from the edges of the image, the lane lines predicted by the trained CLRNet should not start from the edges, right?
![1700907721778](https://github.com/Sephirex-X/ADNet/assets/111288355/42c7cf0a-7f26-434e-92cd-7535931a08e4)
![1700907721778](https://github.com/Sephirex-X/ADNet/assets/111288355/cfeffd8c-905d-435a-8773-e28746baf6a6)

**Comment by Sephirex-X** [comment]
@UcasCore 
Thank u for ur attention. Anchors from clrnet are indeed learnable, since the code from their works is originally implemented using start points from edge, we follow their practice on our implementation without additional modifications, therefore having this results. Naturally this comparison is not fair, therefore we provided additional results on Tab.2 in the paper marked by “*”, which means we moved our start points to the edge just like clrnet does. Fine tuning on clrnet may having better visualization results but out of the scope of our work. 
Hope it can help :)

**Comment by Core9724** [comment]
Thank you for your reply. Another question is: In the introduction section of your paper, you mentioned that the accuracy of the keypoint based lane detection algorithm highly relies on the resolution of the input image, which I don't quite understand. Could you explain in detail why this is so?

**Comment by Sephirex-X** [comment]
> Thank you for your reply. Another question is: In the introduction section of your paper, you mentioned that the accuracy of the keypoint based lane detection algorithm highly relies on the resolution of the input image, which I don't quite understand. Could you explain in detail why this is so?

Technically detail can be found on paper.
